name: 'id_stitching'
version: '1.1.2'
config-version: 2

profile: 'default'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

# leaving vars blank (to be controlled w/in dbt-project that loads this package)
vars:
  id-columns: ()
  tables-to-include: ()
  schemas-to-include: ()
