version: 2

sources:
  - name: INFORMATION_SCHEMA
    tables:
      - name: COLUMNS

models:
  - name: queries
    columns:
      - name: sql_to_run
        tests:
          - unique
          - not_null
  - name: edges
    columns:
      - name: rudder_id
        tests:
          - not_null
      - name: original_rudder_id
        tests:
          - not_null
      - name: node_a
        tests:
          - not_null
      - name: node_a_label
        tests:
          - not_null
      - name: node_b
        tests:
          - not_null
      - name: node_b_label
        tests:
          - not_null
      - name: node_timestamp
        tests:
          - not_null
  - name: check_edges
    columns:
      - name: consolidation_needed
        tests:
          - not_null
      - name: rows_to_update
        tests:
          - not_null
  - name: id_graph
    columns:
      - name: rudder_id
        tests:
          - not_null
      - name: node
        tests:
          - unique
          - not_null
      - name: labels
        tests:
          - not_null
      - name: latest_timestamp
        tests:
          - not_null
